# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='Gender',
        ),
        migrations.AddField(
            model_name='temp',
            name='userType',
            field=models.CharField(choices=[('1', '\u7ba1\u7406\u5458'), ('2', '\u666e\u901a\u7528\u6237'), ('3', '\u8d85\u7ea7\u7ba1\u7406\u5458')], default=1, max_length=20),
        ),
    ]
