# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170929_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostanme', models.CharField(max_length=30)),
                ('ip', models.CharField(max_length=30)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.GroupName')),
            ],
        ),
    ]
