# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_groupname_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='username',
            old_name='hostanme',
            new_name='hostname',
        ),
    ]
