# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20171009_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModleForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('ipaddr', models.GenericIPAddressField()),
            ],
        ),
    ]
